import javax.swing.*;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.border.*;
import java.awt.FlowLayout;
import javax.swing.JFrame;
import javax.swing.JFormattedTextField;
import javax.swing.text.MaskFormatter;
import java.text.ParseException;

import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.Arrays;


public class ConsultForm 
{
    private Usuarios u = new Usuarios();
    ConsultTable ct;

    private JPanel consult_form;
    private JFormattedTextField tf_1;
    private JFormattedTextField hour_field;
    private JComboBox medic_list;
    private JButton add_consulta;

    private String pacient_name;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        try {
            $$$setupUI$$$();
        } catch (ParseException e) {e.printStackTrace();}
        tf_1.setText("dd/mm/aaaa");
    }

    public ConsultForm(String pacient, ConsultTable ct)
    {
        this.pacient_name = pacient;
        this.ct = ct;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()throws ParseException {
        consult_form = new JPanel();
        consult_form.setLayout(new GridBagLayout());
        consult_form.setBorder(BorderFactory.createTitledBorder(null, "Marcar consulta", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-16777216)));
        final JLabel label1 = new JLabel();
        label1.setText("Data da consulta");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        consult_form.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Hora");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        consult_form.add(label2, gbc);
        MaskFormatter data = new MaskFormatter("##/##/####");
            data.setValidCharacters("0123456789");
        tf_1 = new JFormattedTextField(data);
        tf_1.setColumns(10);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        consult_form.add(tf_1, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Médico");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        consult_form.add(label3, gbc);
        medic_list = new JComboBox(u.getMedicList());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.gridwidth = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        consult_form.add(medic_list, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setPreferredSize(new Dimension(5, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        consult_form.add(panel1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel2.setPreferredSize(new Dimension(5, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        consult_form.add(panel2, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        panel3.setPreferredSize(new Dimension(5, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        consult_form.add(panel3, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        panel4.setPreferredSize(new Dimension(0, 10));
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        consult_form.add(panel4, gbc);
        add_consulta = new JButton();
        add_consulta.setText("Marcar");
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        consult_form.add(add_consulta, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        consult_form.add(panel5, gbc);
        MaskFormatter hour = new MaskFormatter("##:##");
            hour.setValidCharacters("0123456789");
        hour_field = new JFormattedTextField(hour);
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        consult_form.add(hour_field, gbc);

        add_consulta.addActionListener(new AddConsultaListener());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return consult_form;
    }

    public class AddConsultaListener implements ActionListener
    {
        @Override
        public void actionPerformed(ActionEvent ev)
        {
            String date = tf_1.getText();
            String hour = hour_field.getText();
            if(ValidDateAndHour.validaData(date, true) == false)
                return;
            if(ValidDateAndHour.validaHora(hour) == false)
                return;
            Consulta c = new Consulta(date, hour, medic_list.getSelectedItem().toString(), pacient_name);
            if(ConsultaHandle.marcarConsulta(c, medic_list.getSelectedItem().toString()) == false) 
            {
                JOptionPane.showMessageDialog(null,"Erro ao marcar consulta","AVISO",JOptionPane.WARNING_MESSAGE);
                return;
            }

            Object[] data = {c.getDataConsultaStr(), c.getHoraConsultaStr(), c.getMedico(), c.getPaciente()};
            
            ct.externalAddOperation(data);
        }
    }
}