import javax.swing.*;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.border.*;

import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.Arrays;

public class GGForm {
    private JPanel gg_form;
    private JTextField user_field;
    private JPasswordField pass_field;
    private JButton adicionarGerenteButton;

    /**fields */
    private String name;
    private String cpf;
    private String rg;
    private String adress;
    private String clt;
    private String da;
    GGDash g;
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }


    public GGForm(String name, String cpf, String rg, String addrs, String clt, String da, GGDash g)
    {
        this.name = name; this.cpf = cpf; this.rg = rg; 
        this.adress = addrs; this.clt = clt; this.da = da;

        this.g = g;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        gg_form = new JPanel();
        gg_form.setLayout(new GridBagLayout());
        gg_form.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), "Gerente Geral", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-16777216)));
        final JLabel label1 = new JLabel();
        label1.setText("Usuário");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gg_form.add(label1, gbc);
        user_field = new JTextField();
        user_field.setColumns(10);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gg_form.add(user_field, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Senha");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gg_form.add(label2, gbc);
        pass_field = new JPasswordField();
        pass_field.setColumns(10);
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gg_form.add(pass_field, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setPreferredSize(new Dimension(5, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        gg_form.add(panel1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel2.setPreferredSize(new Dimension(10, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        gg_form.add(panel2, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        panel3.setPreferredSize(new Dimension(5, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        gg_form.add(panel3, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        panel4.setPreferredSize(new Dimension(0, 10));
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        gg_form.add(panel4, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridBagLayout());
        panel5.setPreferredSize(new Dimension(10, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        gg_form.add(panel5, gbc);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridBagLayout());
        panel6.setPreferredSize(new Dimension(10, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        gg_form.add(panel6, gbc);
        adicionarGerenteButton = new JButton();
        adicionarGerenteButton.setText("Adicionar Gerente");
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gg_form.add(adicionarGerenteButton, gbc);

        adicionarGerenteButton.addActionListener(new AddGGListener());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return gg_form;
    }

    class AddGGListener implements ActionListener 
    {
        @Override
        public void actionPerformed(ActionEvent ev)
        {
            System.out.println(name + cpf + rg + adress + clt + da);

            Gerente_Geral gg = new Gerente_Geral(name, cpf, rg, adress, clt, da); 
            String pass = new String(pass_field.getPassword());
            //System.out.println("user before: "+user_field.getText().length() +"senha before:"+pass.length());
            /**
             * validando usario e senha
             */
            if(user_field.getText().length() == 0)
            {
                JOptionPane.showMessageDialog(null,"Usuário em branco!","AVISO",JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(pass.length() == 0)
            {
                JOptionPane.showMessageDialog(null,"Senha em branco!","AVISO",JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            Usuario u = new Usuario(user_field.getText(), pass);
            System.out.println("user: "+u.getUsuario() +"senha:"+u.getSenha());

            Object[] data = {u.getUsuario(), u.getSenha(),"Gerente Geral"};

            if(u.cadastraUsuario(gg) != -1)  
            {
                JOptionPane.showMessageDialog(null, "Usuário "+ u.getUsuario() + " Já cadastrado!.");
                return;
            }
            Usuarios.addUsuario(u);
            g.users_model.addRow(data);
            g.users_table.clearSelection();
            g.users_model.fireTableDataChanged();
        }
    }

}
