import javax.swing.*;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.border.*;

import javax.swing.JFormattedTextField;
import javax.swing.text.MaskFormatter;
import java.text.ParseException;


import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.Arrays;

public class PacientForm 
{
    //system objects
    Paciente p;

    private JPanel patient_form;
    private JTextField textField1;
    private JFormattedTextField textField2;
    private JFormattedTextField textField3;
    private JTextField textField4;
    private JFormattedTextField textField5;
    private JFormattedTextField  textField6;
    private JButton adicionarButton;
    private JButton limparButton;

    PacientTable pt;

    public void clearFields()
    {
        textField1.setText(""); textField2.setText(""); textField3.setText("");
        textField4.setText(""); textField5.setText(""); textField6.setText("");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        try {
            $$$setupUI$$$();
        } catch (ParseException e) {e.printStackTrace();}
    }

    public PacientForm(PacientTable p)
    {
        this.pt = p;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() throws ParseException {
        patient_form = new JPanel();
        patient_form.setLayout(new GridBagLayout());
        patient_form.setBorder(BorderFactory.createTitledBorder(null, "Cadastrar paciente", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-16777216)));
        final JLabel label1 = new JLabel();
        label1.setText("Nome");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        patient_form.add(label1, gbc);
        textField1 = new JTextField();
        textField1.setColumns(20);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        patient_form.add(textField1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("CPF");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        patient_form.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Endereço");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        patient_form.add(label3, gbc);
        textField4 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.gridwidth = 14;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        patient_form.add(textField4, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Nascimento");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        patient_form.add(label4, gbc);
        MaskFormatter anonasc = new MaskFormatter("####");
            anonasc.setValidCharacters("0123456789");
        textField5 = new JFormattedTextField(anonasc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        patient_form.add(textField5, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Telefone");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        patient_form.add(label5, gbc);
        MaskFormatter tel = new MaskFormatter("##-#-####-####");
            tel.setValidCharacters("0123456789");
        textField6 = new JFormattedTextField(tel);
        textField6.setColumns(10);
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 4;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        patient_form.add(textField6, gbc);
        MaskFormatter cpf = new MaskFormatter("###.###.###-##");
            cpf.setValidCharacters("0123456789");
        textField2 = new JFormattedTextField(cpf);
        textField2.setColumns(12);
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        patient_form.add(textField2, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("RG");
        gbc = new GridBagConstraints();
        gbc.gridx = 9;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        patient_form.add(label6, gbc);
        MaskFormatter rg = new MaskFormatter("##.###.###");
            rg.setValidCharacters("0123456789");
        textField3 = new JFormattedTextField(rg);
        textField3.setColumns(12);
        gbc = new GridBagConstraints();
        gbc.gridx = 11;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        patient_form.add(textField3, gbc);
        adicionarButton = new JButton();
        adicionarButton.setText("Adicionar");
        gbc = new GridBagConstraints();
        gbc.gridx = 15;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        patient_form.add(adicionarButton, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setPreferredSize(new Dimension(0, 10));
        panel1.setRequestFocusEnabled(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        patient_form.add(panel1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel2.setPreferredSize(new Dimension(5, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.BOTH;
        patient_form.add(panel2, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        panel3.setPreferredSize(new Dimension(5, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        patient_form.add(panel3, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        panel4.setPreferredSize(new Dimension(5, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 12;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.BOTH;
        patient_form.add(panel4, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridBagLayout());
        panel5.setPreferredSize(new Dimension(5, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.BOTH;
        patient_form.add(panel5, gbc);
        limparButton = new JButton();
        limparButton.setText("Limpar");
        gbc = new GridBagConstraints();
        gbc.gridx = 12;
        gbc.gridy = 6;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        patient_form.add(limparButton, gbc);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridBagLayout());
        panel6.setPreferredSize(new Dimension(5, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 14;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.BOTH;
        patient_form.add(panel6, gbc);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new GridBagLayout());
        panel7.setPreferredSize(new Dimension(0, 10));
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        patient_form.add(panel7, gbc);
        final JPanel panel8 = new JPanel();
        panel8.setLayout(new GridBagLayout());
        panel8.setPreferredSize(new Dimension(0, 10));
        gbc = new GridBagConstraints();
        gbc.gridx = 13;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.BOTH;
        patient_form.add(panel8, gbc);
        final JPanel panel9 = new JPanel();
        panel9.setLayout(new GridBagLayout());
        panel9.setPreferredSize(new Dimension(5, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 10;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        patient_form.add(panel9, gbc);
        final JPanel panel10 = new JPanel();
        panel10.setLayout(new GridBagLayout());
        panel10.setPreferredSize(new Dimension(5, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.BOTH;
        patient_form.add(panel10, gbc);
        adicionarButton.addActionListener(new AddPacienteListener());
        limparButton.addActionListener(new LimparPacienteListener());
        textField5.setText("aaaa");
        textField6.setText("DD000000000");
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return patient_form;
    }

    class AddPacienteListener implements ActionListener
    {
        @Override
        public void actionPerformed(ActionEvent ev)
        {
            int ano = Integer.parseInt(textField5.getText());
            if(ano > 999999999 || ano < 1 )
            {   
                JOptionPane.showMessageDialog(null,"Formato do ano de nascimento incorreto","AVISO",JOptionPane.WARNING_MESSAGE);
                clearFields();
                return;
            }
            System.out.println(textField6.getText());
            if(textField6.getText().length() < 14 || textField6.getText().length() > 14)
            {
                JOptionPane.showMessageDialog(null,"Formato do telefone incorreto","AVISO",JOptionPane.WARNING_MESSAGE);
                clearFields();
                return;
            }
            System.out.println(textField5.getText());
            p = new Paciente(textField1.getText(), textField2.getText(), textField3.getText(), 
            textField4.getText(), textField5.getText(), textField6.getText());
            Object[] data = 
            {
                p.getName(), p.getCpf(), p.getRg(), 
                p.getAdress(), p.getNascimento(), p.getTelefone(), p.getPrimeira_consultaStr()
            };
            
            if(PacienteHandle.add(p) == true)
            {   
                System.out.println("true");
                pt.externalAddOperation(data);
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao adicionar o paciente "+ p.getName() + "!");
                return;
            }
        }
    }

    class LimparPacienteListener implements ActionListener
    {
        @Override
        public void actionPerformed(ActionEvent ev)
        {
            clearFields();
            textField5.setText("aaaa");
            textField6.setText("DD000000000");
        }
    }
}
